// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcppChangeVector
LogicalVector rcppChangeVector(int vectorSize);
RcppExport SEXP rcppTests_rcppChangeVector(SEXP vectorSizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type vectorSize(vectorSizeSEXP);
    rcpp_result_gen = Rcpp::wrap(rcppChangeVector(vectorSize));
    return rcpp_result_gen;
END_RCPP
}
// rcppChangeVectorReference
LogicalVector rcppChangeVectorReference(int vectorSize);
RcppExport SEXP rcppTests_rcppChangeVectorReference(SEXP vectorSizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type vectorSize(vectorSizeSEXP);
    rcpp_result_gen = Rcpp::wrap(rcppChangeVectorReference(vectorSize));
    return rcpp_result_gen;
END_RCPP
}
